// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // 通常のクライアント (実行時): pooled connection を優先。
    // マイグレーション CLI 実行時は DIRECT_URL を優先する (pgbouncer はマイグレーション非対応)。
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
